# This is a basic workflow to help you get started with Actions
name: AUTOMATIC_DEPLOY

on:
  push:
    branches:
      - main  # main分支有push操作时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # 找Hugo主題(true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.89.4' # hugo 版本
          extended: true  # 非extended版本注释该行

      - name: Build
        run: hugo --minify --theme book

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUGO_DEPLOY_TOKEN }}
          PUBLISH_BRANCH: gh-pages  # 推送到 gh-pages 分支
          PUBLISH_DIR: ./public     # hugo 生成的目录
          commit_message: ${{ github.event.head_commit.message }}
